"""Explicitly refresh Windows x64/CPython 3.14 wheel hashes. Review before commit."""
import json
import urllib.request
from pathlib import Path

PINS = {"pip": "26.2.1", "pyinstaller": "6.22.3", "pillow": "12.3.0",
        "defusedxml": "0.7.1", "altgraph": "0.17.5", "packaging": "26.3",
        "pefile": "2024.8.26", "pyinstaller-hooks-contrib": "2026.7",
        "pywin32-ctypes": "0.2.3", "setuptools": "84.0.0"}


def main():
    lines = ["# Windows x64 / CPython 3.14.7; generated by tools/refresh_build_lock.py.",
             "# Builds consume this reviewed lock; they never regenerate it.", ""]
    for name, version in PINS.items():
        with urllib.request.urlopen(f"https://pypi.org/pypi/{name}/{version}/json", timeout=30) as response:
            data = json.load(response)
        wheels = [entry for entry in data["urls"]
                  if entry["filename"].endswith(".whl") and not entry.get("yanked")
                  and (entry["filename"].endswith("-none-any.whl")
                       or entry["filename"].endswith("-none-win_amd64.whl")
                       or entry["filename"].endswith("-cp314-cp314-win_amd64.whl"))]
        hashes = sorted({entry["digests"]["sha256"] for entry in wheels})
        if not hashes:
            raise RuntimeError(f"No compatible Windows wheel: {name} {version}")
        lines.append(f"{name}=={version} " + " ".join(f"--hash=sha256:{value}" for value in hashes))
    (Path(__file__).resolve().parent.parent / "requirements-build.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
