"""Generate Windows resources from the same version used by the desktop client."""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from sls_version import VERSION, VERSION_TUPLE


def main():
    prerelease_flag = 0x2 if any(label in VERSION.lower() for label in ("alpha", "beta", "rc", "dev")) else 0
    for filename, name, description in (
        ("version_info_app.txt", "SLS_Mass_Notify", "SLS Mass Notify desktop client"),
        ("version_info_installer.txt", "SLS_Mass_Notify_Installer", "SLS Mass Notify installer"),
    ):
        values = {"CompanyName": "Southland Servers Group", "FileDescription": description,
                  "FileVersion": VERSION, "InternalName": name,
                  "LegalCopyright": "Copyright (c) Southland Servers Group",
                  "OriginalFilename": name + ".exe", "ProductName": "SouthlandServers Mass Notification App",
                  "ProductVersion": VERSION}
        strings = ",\n".join(f"        StringStruct({key!r}, {value!r})" for key, value in values.items())
        resource = f"""# Generated by tools/write_version_info.py from sls_version.py.
VSVersionInfo(
  ffi=FixedFileInfo(filevers={VERSION_TUPLE!r}, prodvers={VERSION_TUPLE!r}, mask=0x3f,
                   flags={prerelease_flag}, OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)),
  kids=[StringFileInfo([StringTable('040904B0', [
{strings}
  ])]), VarFileInfo([VarStruct('Translation', [1033, 1200])])]
)
"""
        (ROOT / filename).write_text(resource, encoding="utf-8")


if __name__ == "__main__":
    main()
